### ISSUE TITLE
AI Provider Dynamic Model List Retrieval Architecture Issue

### ISSUE THREAD

**Issue by mouimet-infinisoft** [stackblitz-labs/bolt.diy#396]
## Problem Statement
Dynamic AI Provider model list retrieval is not working.

## Related with
#307 : Issue : Add Together AI Integration
#385 : PR : feat: add Together AI integration and provider implementation guide
[AI Provider Implementation Guide](https://github.com/coleam00/bolt.new-any-llm/pull/385#issue-2685390870)

## Cause
- Dynamic model list retrieval fails due to client-side execution of server operations
- Security context violations when accessing API keys
- Environment variable access in wrong context

### What Works
- ✅ Static provider lists
- ✅ Hardcoded configurations
- ✅ Public URL providers

### What Fails
- ❌ Dynamic provider discovery non-functional
- ❌ Silent failures in API calls
- ❌ Missing security context
- ❌ Environment variables undefined

## Files Affected
```
app/utils/constants.ts
app/lib/.server/llm/api-key.ts
app/entry.server.tsx
```

## Code Example
```typescript
// In app/utils/constants.ts
const PROVIDER_LIST: ProviderInfo[] = [
  {
    name: 'Provider',
    getDynamicModels: async () => {
      // ❌ Fails: No access to env variables
      const apiKey = import.meta.env.PROVIDER_API_KEY;
      const baseUrl = import.meta.env.PROVIDER_BASE_URL;
      
      // ❌ Fails: Cannot make authenticated requests
      const response = await fetch(`${baseUrl}/models`, {
        headers: { Authorization: `Bearer ${apiKey}` }
      });
    }
  }
];
```

### 1. Provider Configuration
- **Base Configuration** (Server-side)
  ```json
  {
    "providers": [
      {
        "id": "provider1",
        "name": "Provider One",
        "baseUrl": "https://api.provider1.com",
        "supportedFeatures": ["chat", "vision"]
      }
    ]
  }
  ```
  - Store in external JSON assets
  - Avoid code rebuilds for new providers
  - Keep sensitive URLs server-side

### 2. Session Management and Server-Side Rehydration
- Cookie-driven configuration:
  ```json
  {
    "selectedProvider": "provider1",
    "selectedModel": "model-name",
    "apiKeys": {
      "provider1": "encrypted-key"
    }
  }
  ```

### 3. Server-Side Update Flow
![Diagram](https://www.plantuml.com/plantuml/svg/VSwnJWCn30RWFKzXklC2Dw2YJcmL9nx092vdDOaZd--glZrgt4EKWSsoF_ltVZPKMqeEJpPH8PWRHihu6HggSUI6rM1to4pLTe0pUFau7abNqZxsyi-so9a9HXEbZhpnY8ugAoTIU3s-TRGrGl18U7wvNn_WeoKqWhRjHAad_We-la5F6634bQ3IvIuMHMEfl-2MCi1XedY6aoYaQyN24OeaolCF_YU_gJI7VjK_7k2TfclI6xsmJVqHftkgQIdv6m00)

### 4. Implementation Details
- **Server-side handling**:
  ```typescript
  async function handleConfigUpdate(request: Request) {
    const cookie = parseCookie(request);
    const providerConfig = cookie.providerConfig;

    // Update available models if API key exists
    if (providerConfig.apiKeys[providerConfig.selectedProvider]) {
      const modelList = await fetchProviderModels(
        providerConfig.selectedProvider,
        providerConfig.apiKeys[providerConfig.selectedProvider]
      );
      
      // Update provider props for rehydration
      return json({
        provider: providerConfig.selectedProvider,
        models: modelList,
        configured: true
      });
    }

    // Fallback to static configuration
    return json({
      provider: providerConfig.selectedProvider,
      models: STATIC_MODEL_LIST[providerConfig.selectedProvider],
      configured: false
    });
  }
  ```

- **Client rehydration**:
  ```typescript
  interface ProviderProps {
    selectedProvider: string;
    availableModels: string[];
    isConfigured: boolean;
  }
  ```

### 5. Key Benefits
- ✅ Server-driven model list updates
- ✅ Automatic rehydration on configuration changes
- ✅ Seamless fallback to static assets
- ✅ No client-side API calls needed

## Benefits
- ✅ Secure API key handling
- ✅ Remove metadata overhead sent to chat API Reduced payload size (~400 bytes/conversation)
- ✅ Better separation of concerns
- ✅ No rebuilds needed for provider changes

## Migration Steps
1. Move provider configs to JSON assets
2. Implement cookies for selected provider / model / API keys
3. Create server-side model fetching
4. Update client to use provided lists
5. Cleanup meta data sent to chat API each message
6. Replace chat API meta data parsing by configuration session storage

**Comment by mouimet-infinisoft** [comment]
# Proposed AI Provider Specification

## Overview
This document outlines the complete specifications for managing AI providers, combining secure API key handling with dynamic model loading capabilities. It addresses the issues identified in the dynamic model loading system while maintaining secure API key management.

## Core Architecture

### High-Level Design
![Diagram](https://www.plantuml.com/plantuml/dsvg/PP3DZjim38JlUWfsxvi7wA7OXO2Wnjfe42Ed8WUjpSP2PCaLwHHkqNSlAJS_HK-6-D4pd7aXTfddCPWFFE28G9FhCBXtGsSV9vVT25qQfnGnSijBGCZOiOkdWCPq8SqzFDdWXKBhUto2NmRWwowdYxmo7AeZE9AFJcrAPu_GSihkX0NOLa6JUWpGOi1EM05DQtxV35hC5yoF1g-x2lPfPgIoBSz_R1iNnM5LsZMAtd21FL8AC_iK2tZRtxstJfsNrNfxdrlN3RXEhHxKEtRlZb1l8XAbakQ_s3R5R_wqsjkxMks9QLMh7-BLTGFNN-clr9S9usjrB5aZ3pbDlfEN01vaQxFP75NXKC7pyoUf4Jwkby1qlO6qJWrhXEgIbAHR67luuNc0ZDzd93OoLov52VxiOXyULD94He1mwKjuwV22SCQ5Z4mKD5i1LVJiNV0_4KODIqR6XLgXfKTnf3dmJN2dv319fmXTQSmqTlsdlkK9sfcHWSubhfumB7sMd-HfNYJEF8O_)

### 2. Server-Side Components

#### Provider Manager
```typescript
class ProviderManager {
  private providers: Map<string, ProviderInfo>;
  private modelCache: ModelCache;
  private keyResolver: KeyResolver;

  async getProviderModels(provider: string, config: ProviderConfig): Promise<ModelInfo[]> {
    const providerInfo = this.providers.get(provider);
    
    if (!providerInfo) {
      throw new Error(`Provider ${provider} not found`);
    }

    // Check cache first
    const cached = await this.modelCache.get(provider);
    if (cached) return cached;

    // Get dynamic models if supported
    if (providerInfo.getDynamicModels && providerInfo.capabilities.supportsDynamicModels) {
      const models = await providerInfo.getDynamicModels(config);
      await this.modelCache.set(provider, models);
      return models;
    }

    return providerInfo.staticModels;
  }
}
```

#### Key Resolution
```typescript
class KeyResolver {
  resolveKey(provider: string, config: ProviderConfig): string | undefined {
    // Priority: User provided > Environment > Default
    return config.apiKeys[provider] || 
           process.env[`${provider.toUpperCase()}_API_KEY`];
  }
}
```

### 3. Client-Side Components

#### Provider Selection Store
```typescript
interface ProviderState {
  selectedProvider: string;
  selectedModel: string;
  availableModels: ModelInfo[];
  isConfigured: boolean;
}

class ProviderStore {
  private state: ProviderState;
  
  async selectProvider(provider: string) {
    const config = this.getConfig();
    
    // Update cookie
    document.cookie = `providerConfig=${JSON.stringify({
      selectedProvider: provider,
      selectedModel: null,
      apiKeys: config.apiKeys
    })}; path=/; Secure; SameSite=Strict; HttpOnly`;

    // Trigger server update
    await this.updateProviderState();
  }

  private async updateProviderState() {
    const response = await fetch('/api/provider/update', {
      method: 'POST',
      credentials: 'include'
    });
    
    const data = await response.json();
    this.state = data;
  }
}
```

### 4. API Routes

```typescript
// Route: /api/provider/update
async function handleProviderUpdate(request: Request) {
  const config = parseProviderConfig(request);
  const provider = config.selectedProvider;
  
  const models = await providerManager.getProviderModels(
    provider,
    config
  );

  return json({
    selectedProvider: provider,
    availableModels: models,
    isConfigured: Boolean(config.apiKeys[provider])
  });
}
```

## Provider Lifecycle

1. **Initial Load**
   - Load static provider configurations
   - Initialize provider manager
   - Setup model cache

2. **Provider Selection**
   - User selects provider in UI
   - Update cookie with selection
   - Trigger server-side update

3. **API Key Management**
   - User enters API key
   - Store in HttpOnly cookie
   - Trigger model list refresh

4. **Model Loading**
   - Check cache for models
   - Fetch dynamic models if supported
   - Update UI with available models

5. **Provider Usage**
   - Resolve API key
   - Initialize model with key
   - Execute model operations

## Migration Guide

### Phase 1: Provider Configuration
1. Move provider configs to JSON assets
2. Implement ProviderManager class
3. Setup model caching system

### Phase 2: State Management
1. Implement cookie-based configuration
2. Create provider store
3. Setup API routes

### Phase 3: UI Updates
1. Update provider selection UI
2. Implement model selector
3. Add configuration status indicators

### Phase 4: Testing & Validation
1. Test provider lifecycle
2. Validate security measures
3. Performance testing
4. Error handling verification

## Security Considerations

1. **API Key Storage**
   - Use HttpOnly cookies
   - Implement key rotation
   - Server-side only key access

2. **Request Validation**
   - Validate provider capabilities
   - Check API key presence
   - Verify model availability

3. **Error Handling**
   - Graceful fallbacks
   - User feedback
   - Logging strategy

## Implementation Checklist

- [ ] Core types and interfaces
- [ ] Provider manager implementation
- [ ] Key resolution system
- [ ] Model caching
- [ ] API routes
- [ ] Client-side store
- [ ] UI components
- [ ] Security measures
- [ ] Error handling
- [ ] Testing suite

## References

1. API Key Management:
```typescript:app/lib/.server/llm/api-key.ts
startLine: 129
endLine: 144
```

2. Provider Configuration:
```typescript:app/utils/constants.ts
startLine: 38
endLine: 279
```

3. Model Types:
```typescript:app/types/model.ts
startLine: 1
endLine: 10
```

This architecture provides a comprehensive solution for both API key management and dynamic model loading while maintaining security and performance considerations.

**Comment by h4de5** [comment]
if this means, that the chat UI no longer directly queries the LLM provider, but uses the server as a kind of proxy, then this would solve most CORS related issues that happen, when trying to access the server on a different local network address.

**Comment by mouimet-infinisoft** [comment]
> if this means, that the chat UI no longer directly queries the LLM provider, but uses the server as a kind of proxy, then this would solve most CORS related issues that happen, when trying to access the server on a different local network address.

Indeed, that is a expected goal, but it falls outside the scope of this issue. In the proposed architecture, I have designed the system to query the LLM from the server side. By centralizing the provider configuration on the server, this approach offers several advantages:

1. **Reduced Overhead**: Avoids sending metadata (e.g., provider, model, API key) with each message, improving efficiency.  
2. **Simplified Implementation**: Eliminates the need for regex parsing to extract details like the provider, model, and API key from messages.  

This design ensures a cleaner, more efficient system while streamlining future development and maintenance. Here is a part of my analysis.

# 🚀 JSON Chat History Optimization: 38.6% Performance Boost

## Overview
A significant optimization in chat history JSON structure, resulting in a 38.6% reduction in data size while maintaining full functionality.

## 🔍 Technical Analysis

### Before & After Message Payload Comparison

Before:
```json
{
    "messages": [
        {
            "role": "user",
            "content": "[Model: meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo]\n\n[Provider: Together]\n\nhello"
        },
        {
            "role": "assistant",
            "content": "Hello! I'm Bolt, your AI assistant. I'm here to help you with any questions or tasks you may have. What's on your mind?"
        },
        {
            "role": "user",
            "content": "[Model: meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo]\n\n[Provider: Together]\n\nmy namew is martin and you ?"
        },
        {
            "role": "assistant",
            "content": "Nice to meet you, Martin! I'm Bolt, an expert AI assistant and senior software developer. I'm here to help you with any coding-related questions, projects, or tasks you may have. What brings you here today, Martin?"
        },
        {
            "role": "user",
            "content": "[Model: meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo]\n\n[Provider: Together]\n\nhi"
        }
    ],
    "apiKeys": {
        "Together": ""
    }
}
```
After:
```json
{
    "messages": [
        {
            "role": "user",
            "content": "hello"
        },
        {
            "role": "assistant",
            "content": "Hello! I'm Bolt, your AI assistant. I'm here to help you with any questions or tasks you may have. What's on your mind?"
        },
        {
            "role": "user",
            "content": "my namew is martin and you ?"
        },
        {
            "role": "assistant",
            "content": "Nice to meet you, Martin! I'm Bolt, an expert AI assistant and senior software developer. I'm here to help you with any coding-related questions, projects, or tasks you may have. What brings you here today, Martin?"
        },
        {
            "role": "user",
            "content": "hi"
        }
    ]
}
```

## 📊 Performance Metrics

### Size Optimization
- **Original Size**: 847 characters
- **Optimized Size**: 520 characters
- **Total Reduction**: 327 characters (38.6%)

### Removed Components
1. **Metadata Headers** (82 chars × 3 messages)
   - Model information
   - Provider details
   - Total: 246 characters
2. **API Configuration** (31 chars)
   - Removed redundant API key structure
 3. **Message Parser**
  - Removed metadata parser to extract provider. models, API key for each message.

### 🎯 Expected Efficiency Improvements
- ⚡ Network Transfer: 38.6% reduction
- 🚄 Parsing Speed: ~40% faster
- 💾 Storage Efficiency: 38.6% space saved

## 💡 Key Benefits
1. No more secrets sent in clear
2. Fix CORS issues
3. Reduced bandwidth consumption
4. Faster message processing
5. Improved storage efficiency
6. Cleaner, more maintainable JSON structure
7. **Enhanced Code Quality and Scalability**  
   - **Reduced Tight Coupling**: Decouples metadata handling from the messaging layer, promoting modular design.  
   - **Separation of Concerns**: Centralizes configuration management, allowing each component to focus on its primary responsibilities.  
   - **Lower Cyclomatic Complexity**: Simplifies code logic by removing the need for regex-based metadata parsing, making the codebase easier to maintain and test.  

## 📈 Impact
This optimization is particularly impactful for:
- High-volume chat applications
- Mobile clients with limited bandwidth
- Systems with storage constraints
- Real-time message processing

**Comment by thecodacus** [comment]
this should fix the dynamic model loading for togather 
#513
